# Generated by Django 3.0.3 on 2020-02-21 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe',
            name='game_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
